# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py38, py39, py310, py311, py312

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312


[testenv]
deps = -r{toxinidir}/requirements.txt
passenv = TOXENV,CI
usedevelop = True

# run the tests
# ... or run any other command line tool you need to run here
commands = pytest
