# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py39, py310, py314

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.14: py314

[testenv:dev]
deps = .[dev]
passenv = TOXENV,CI
basepython = python3
usedevelop = True
commands = pytest
